In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/public_school_data.csv', skiprows=6)
df.head(3)

,School Name,State Name [Public School] Latest available year,School ID (12-digit) - NCES Assigned [Public School] Latest available year,Black or African American Students [Public School] 2024-25,Black or African American Students [Public School] 2023-24,Black or African American Students [Public School] 2022-23,Black or African American Students [Public School] 2021-22,Black or African American Students [Public School] 2020-21,Black or African American Students [Public School] 2019-20,Black or African American Students [Public School] 2018-19,...,Free and Reduced Lunch Students [Public School] 2017-18,Free and Reduced Lunch Students [Public School] 2016-17,Free and Reduced Lunch Students [Public School] 2015-16,Free and Reduced Lunch Students [Public School] 2014-15,Free and Reduced Lunch Students [Public School] 2013-14,Free and Reduced Lunch Students [Public School] 2012-13,Free and Reduced Lunch Students [Public School] 2011-12,Free and Reduced Lunch Students [Public School] 2010-11,Free and Reduced Lunch Students [Public School] 2009-10,Free and Reduced Lunch Students [Public School] 2008-09
0,'O ME-NOK LEARNING CENTER,California,6.107700e+10,0,0,0,–,–,0,–,...,58,102,77,90,68,67,‡,80,82,97
1,1 LT CHARLES W. WHITCOMB SCHOOL,Massachusetts,2.507320e+11,60,45,40,33,42,44,46,...,–,–,–,717,687,654,618,613,561,490
2,100 BLACK MEN OF THE BAY AREA COMMUNITY,California,6.280501e+10,†,†,†,†,†,†,†,...,†,†,†,†,47,18,†,†,†,†

In [3]:
schools_info = df.loc[:, 
    ["School ID (12-digit) - NCES Assigned [Public School] Latest available year",
    "School Name", "State Name [Public School] Latest available year"]
]

schools_columns = {
    "School ID (12-digit) - NCES Assigned [Public School] Latest available year" : "school_id",
    "School Name": "school_name",
    "State Name [Public School] Latest available year": "state_name"
}

schools_info = schools_info.rename(columns=schools_columns)
schools_info['school_id'] = schools_info['school_id'].astype(str)
schools_info.head(2)

        school_id                      school_name     state_name
0   61077001195.0        'O ME-NOK LEARNING CENTER     California
1  250732002639.0  1 LT CHARLES W. WHITCOMB SCHOOL  Massachusetts

In [4]:
school_years = [
    '2008-09', '2009-10', '2010-11', '2011-12',
    '2012-13', '2013-14', '2014-15', '2015-16',
    '2016-17', '2017-18', '2018-19', '2019-20',
    '2020-21', '2021-22', '2022-23', '2023-24',
    '2024-25'
]

def data_transformer(row, year: str = None):
    new_row = {
        "school_id": row["School ID (12-digit) - NCES Assigned [Public School] Latest available year"],
        "year": year,
        "white_students": row[f"White Students [Public School] {year}"],
        "black_students": row[f"Black or African American Students [Public School] {year}"],
        "total_students": row[f"Total Race/Ethnicity [Public School] {year}"],
        "free_and_reduced_lunch": row[f"Free and Reduced Lunch Students [Public School] {year}"]
    }
    return new_row

racial_data = pd.DataFrame(
    data_transformer(row, year)
    for _, row in df.iterrows()
    for year in school_years
)
racial_data["school_id"] = racial_data["school_id"].astype(str)
racial_data.head(2)

,school_id,year,white_students,black_students,total_students,free_and_reduced_lunch
0,61077001195.0,2008-09,33,0,114,97
1,61077001195.0,2009-10,32,0,96,82